// Code generated by "gocqlx/cmd/schemagen"; DO NOT EDIT.

package scylla

import (
	"github.com/scylladb/gocqlx/v3/table"
	"time"
)

// Table models.
var (
	GocqlxMigrate = table.New(table.Metadata{
		Name: "gocqlx_migrate",
		Columns: []string{
			"checksum",
			"done",
			"end_time",
			"name",
			"start_time",
		},
		PartKey: []string{
			"name",
		},
		SortKey: []string{},
	})

	MessagesByChat = table.New(table.Metadata{
		Name: "messages_by_chat",
		Columns: []string{
			"chat_id",
			"created_at",
			"data",
			"data_type",
			"id",
			"quoted_id",
			"sender_id",
		},
		PartKey: []string{
			"chat_id",
		},
		SortKey: []string{
			"created_at",
			"id",
		},
	})
)

// Table structs.
type GocqlxMigrateStruct struct {
	Checksum  string
	Done      int32
	EndTime   time.Time
	Name      string
	StartTime time.Time
}
type MessagesByChatStruct struct {
	ChatId    [16]byte
	CreatedAt time.Time
	Data      string
	DataType  int16
	Id        [16]byte
	QuotedId  [16]byte
	SenderId  [16]byte
}
