// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package pgsql

import (
	"context"

	"github.com/google/uuid"
)

const addUser = `-- name: AddUser :exec
INSERT INTO chat_members (chat_id, user_id)
VALUES ($1, $2)
`

type AddUserParams struct {
	ChatID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.Exec(ctx, addUser, arg.ChatID, arg.UserID)
	return err
}

const claimDMChat = `-- name: ClaimDMChat :one
INSERT INTO dm_chats (user_a, user_b, chat_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_a, user_b) DO NOTHING
RETURNING chat_id
`

type ClaimDMChatParams struct {
	UserA  uuid.UUID
	UserB  uuid.UUID
	ChatID uuid.UUID
}

func (q *Queries) ClaimDMChat(ctx context.Context, arg ClaimDMChatParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimDMChat, arg.UserA, arg.UserB, arg.ChatID)
	var chat_id uuid.UUID
	err := row.Scan(&chat_id)
	return chat_id, err
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats (type, name, logo)
VALUES ($1, $2, $3)
RETURNING id, type, name, logo
`

type CreateChatParams struct {
	Type int16
	Name *string
	Logo *string
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.Type, arg.Name, arg.Logo)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Logo,
	)
	return i, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chat_members
WHERE chat_id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, chatID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChat, chatID)
	return err
}

const getChat = `-- name: GetChat :one
SELECT id, type, name, logo FROM chats
WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Logo,
	)
	return i, err
}

const getDMChat = `-- name: GetDMChat :one
SELECT chat_id FROM dm_chats
WHERE user_a = $1 AND user_b = $2
`

type GetDMChatParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

func (q *Queries) GetDMChat(ctx context.Context, arg GetDMChatParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDMChat, arg.UserA, arg.UserB)
	var chat_id uuid.UUID
	err := row.Scan(&chat_id)
	return chat_id, err
}

const isChatMember = `-- name: IsChatMember :one
SELECT EXISTS(
    SELECT 1 FROM chat_members
    WHERE chat_id = $1 AND user_id = $2
) AS is_member
`

type IsChatMemberParams struct {
	ChatID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatMember, arg.ChatID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const removeUser = `-- name: RemoveUser :exec
DELETE FROM chat_members
WHERE chat_id = $2 AND user_id = $1
`

type RemoveUserParams struct {
	UserID uuid.UUID
	ChatID uuid.UUID
}

func (q *Queries) RemoveUser(ctx context.Context, arg RemoveUserParams) error {
	_, err := q.db.Exec(ctx, removeUser, arg.UserID, arg.ChatID)
	return err
}
