// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package pgsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDMChat = `-- name: ClaimDMChat :one
INSERT INTO dm_chats (user_a, user_b, chat_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_a, user_b) DO NOTHING
RETURNING chat_id
`

type ClaimDMChatParams struct {
	UserA  pgtype.UUID
	UserB  pgtype.UUID
	ChatID pgtype.UUID
}

func (q *Queries) ClaimDMChat(ctx context.Context, arg ClaimDMChatParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimDMChat, arg.UserA, arg.UserB, arg.ChatID)
	var chat_id pgtype.UUID
	err := row.Scan(&chat_id)
	return chat_id, err
}

const getChat = `-- name: GetChat :one
SELECT id, type, name, logo FROM chats
WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id pgtype.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Logo,
	)
	return i, err
}

const getDMChat = `-- name: GetDMChat :one
SELECT chat_id FROM dm_chats
WHERE user_a = $1 AND user_b = $2
`

type GetDMChatParams struct {
	UserA pgtype.UUID
	UserB pgtype.UUID
}

func (q *Queries) GetDMChat(ctx context.Context, arg GetDMChatParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDMChat, arg.UserA, arg.UserB)
	var chat_id pgtype.UUID
	err := row.Scan(&chat_id)
	return chat_id, err
}

const insertChat = `-- name: InsertChat :one
INSERT INTO chats (type, name, logo)
VALUES ($1, null, null)
RETURNING id
`

func (q *Queries) InsertChat(ctx context.Context, type_ int16) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertChat, type_)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertChatMember = `-- name: InsertChatMember :exec
INSERT INTO chat_members (chat_id, user_id)
VALUES ($1, $2)
`

type InsertChatMemberParams struct {
	ChatID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) InsertChatMember(ctx context.Context, arg InsertChatMemberParams) error {
	_, err := q.db.Exec(ctx, insertChatMember, arg.ChatID, arg.UserID)
	return err
}

const isChatMember = `-- name: IsChatMember :one
SELECT EXISTS(
    SELECT 1 FROM chat_members
    WHERE chat_id = $1 AND user_id = $2
) AS is_member
`

type IsChatMemberParams struct {
	ChatID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatMember, arg.ChatID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}
