// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friendship.sql

package pgsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendship = `-- name: CreateFriendship :exec
INSERT INTO friendships (user_a, user_b, status)
VALUES ($1, $2, $3)
ON CONFLICT (user_a, user_b) DO NOTHING
`

type CreateFriendshipParams struct {
	UserA  pgtype.UUID
	UserB  pgtype.UUID
	Status int16
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error {
	_, err := q.db.Exec(ctx, createFriendship, arg.UserA, arg.UserB, arg.Status)
	return err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE user_a = $1 AND user_b = $2
`

type DeleteFriendshipParams struct {
	UserA pgtype.UUID
	UserB pgtype.UUID
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.Exec(ctx, deleteFriendship, arg.UserA, arg.UserB)
	return err
}

const getFriendship = `-- name: GetFriendship :one
SELECT user_a, user_b, status, created_at FROM friendships
WHERE user_a = $1 AND user_b = $2
`

type GetFriendshipParams struct {
	UserA pgtype.UUID
	UserB pgtype.UUID
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendship, arg.UserA, arg.UserB)
	var i Friendship
	err := row.Scan(
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :exec
UPDATE friendships
SET status = $3
WHERE user_a = $1 AND user_b = $2
`

type UpdateFriendshipStatusParams struct {
	UserA  pgtype.UUID
	UserB  pgtype.UUID
	Status int16
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) error {
	_, err := q.db.Exec(ctx, updateFriendshipStatus, arg.UserA, arg.UserB, arg.Status)
	return err
}
