// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgsql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID   pgtype.UUID
	Type int16
	Name pgtype.Text
	Logo pgtype.Text
}

type ChatMember struct {
	ChatID   pgtype.UUID
	UserID   pgtype.UUID
	JoinedAt pgtype.Timestamptz
}

type DmChat struct {
	UserA  pgtype.UUID
	UserB  pgtype.UUID
	ChatID pgtype.UUID
}

type Friendship struct {
	UserA     pgtype.UUID
	UserB     pgtype.UUID
	Status    int16
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID       pgtype.UUID
	Nickname string
	Email    string
	Avatar   pgtype.Text
}
