// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgsql

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID   uuid.UUID
	Type int16
	Name *string
	Logo *string
}

type ChatMember struct {
	ChatID   uuid.UUID
	UserID   uuid.UUID
	JoinedAt pgtype.Timestamptz
}

type DmChat struct {
	UserA  uuid.UUID
	UserB  uuid.UUID
	ChatID uuid.UUID
}

type Friendship struct {
	UserA     uuid.UUID
	UserB     uuid.UUID
	Status    int16
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID uuid.UUID
}
