// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimDMChat(ctx context.Context, arg ClaimDMChatParams) (pgtype.UUID, error)
	CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error
	DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error
	GetChat(ctx context.Context, id pgtype.UUID) (Chat, error)
	GetDMChat(ctx context.Context, arg GetDMChatParams) (pgtype.UUID, error)
	GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertChat(ctx context.Context, type_ int16) (pgtype.UUID, error)
	InsertChatMember(ctx context.Context, arg InsertChatMemberParams) error
	IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error)
	UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) error
}

var _ Querier = (*Queries)(nil)
