// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package pgsql

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id)
VALUES ($1)
`

func (q *Queries) CreateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, createUser, id)
	return err
}
